#!/usr/bin/env ruby

DIGIT_NAMES = %w[zero one two three four five six seven eight nine].freeze

def match(text)
  DIGIT_NAMES.index.with_index do |name, index|
    text.start_with?(name) || text.start_with?(index.to_s)
  end
end

def calibrate(line)
  0.upto(line.size - 1)
   .map { |index| match(line[index..]) }
   .compact
end

ARGF.read.split("\n")
    .map { |line| calibrate(line) }
    .map { |digits| "#{digits[0]}#{digits[-1]}".to_i }
    .sum
    .then(&method(:puts))
