#!/usr/bin/env ruby

class Test2022Day04Part1 < Minitest::Test
  def test_example
    assert_equal '2', solve(<<~INPUT)
      2-4,6-8
      2-3,4-5
      5-7,7-9
      2-8,3-7
      6-6,4-6
      2-6,4-8
    INPUT
  end

  def test_input
    assert_equal '511', solve(input)
  end
end
